# Generated by Django 3.1.2 on 2020-10-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='w_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='w_position',
            new_name='position',
        ),
        migrations.AddField(
            model_name='worker',
            name='premiums',
            field=models.ManyToManyField(to='worker.Premium'),
        ),
    ]
