# Generated by Django 3.1.2 on 2020-12-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20201026_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.level'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='worker.Tax'),
        ),
    ]
